### ISSUE TITLE
rails 7.2.0 problem: NameError: undefined method `validate_find_options' 

### ISSUE THREAD

**Issue by fmorton** [ActsAsParanoid/acts_as_paranoid#342]
Moving from rails 7.1.3.4 to 7.2.0, getting this message:

NameError: undefined method `validate_find_options' for class `#<Class:ActiveRecord::Base>' (NameError)

            alias_method :validate_find_options_without_deleted, :validate_find_options
            ^^^^^^^^^^^^

**Comment by mvz** [comment]
That does not seem to be an error in acts_as_paranoid. Which file does this error occur in?

**Comment by navidemad** [comment]
```
/Users/dev/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:42:in `alias_method': undefined method `validate_find_options' for class `#<Class:ActiveRecord::Base>' (NameError)

  alias_method :validate_find_options_without_deleted, :validate_find_options
  ^^^^^^^^^^^^
from /Users/dev/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:42:in `singleton class'
from /Users/dev/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:41:in `included'
from /Users/dev/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:166:in `include'
from /Users/dev/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:166:in `<main>'
```

But i am getting acts_as_paranoid 0.3.1, when i am trying to lock it the latest 0.10.1, i am getting:
```
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Could not find compatible versions

Because acts_as_paranoid >= 0.9.0 depends on activesupport >= 6.1, < 7.2
  and rails >= 7.2.0 depends on activesupport = 7.2.0,
  acts_as_paranoid >= 0.9.0 is incompatible with rails >= 7.2.0.
So, because Gemfile depends on rails ~> 7.2.0
  and Gemfile depends on acts_as_paranoid = 0.10.1,
  version solving has failed.
```

**Comment by mvz** [comment]
I just released acts_as_paranoid 0.10.2 with support for Rails 7.2.

**Comment by fmorton** [comment]
Thanks for fixing this so quickly.
