### ISSUE TITLE
Failed to destroy after upgrading to 0.8

### ISSUE THREAD

**Issue by tomcoquery** [ActsAsParanoid/acts_as_paranoid#351]
I have a setup like this : 
```
class Program < ApplicationRecord

  has_many :collaborations, foreign_key: "program_id", dependent: :destroy

  before_destroy :destroy_collaborations

  def destroy_collaborations
    reload.collaborations.each do |collaboration|
      collaboration.skip_before_destroy = true
      collaboration.destroy
    end
  end
end
```

```
class Collaboration < ApplicationRecord
  attr_accessor :skip_before_destroy

  before_destroy :program_still_have_collaborator?

  def program_still_have_collaborator?
    if program.reload.collaborations == [self]
      errors.add(:program, :program_without_collaborator)
      throw(:abort) unless skip_before_destroy
    end
  end
end
```

I upgraded to rails 7 and thus acts_as_paranoid 0.8. However, when i try to destroy a program, i constantly get the error "Failed to destroy" error because of my Collaboration before_destroy callback. I did not have this issue before upgrading

**Comment by mvz** [comment]
Hi @tomcoquery, I have a few questions that will help me debug this:

1. Which of these classes has `acts_as_paranoid`?
2. What is the backtrace for the "Failed to destroy" error?
3. Does it still work if you don't upgrade to Rails 7 but still use acts_as_paranoid 0.8?

**Comment by tomcoquery** [comment]
Hi, thanks for your reply. 

1. Both classes have `acts_as_paranoid`

2. Here's the full backtrace :

```
# /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/acts_as_paranoid-0.10.2/lib/acts_as_paranoid/core.rb:165:in `destroy!'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/associations/has_many_association.rb:124:in `each'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/associations/has_many_association.rb:124:in `delete_records'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/associations/collection_association.rb:390:in `remove_records'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/associations/collection_association.rb:381:in `block in delete_or_destroy'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/database_statements.rb:314:in `transaction'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/transactions.rb:209:in `transaction'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/associations/collection_association.rb:308:in `transaction'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/associations/collection_association.rb:381:in `delete_or_destroy'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/associations/collection_association.rb:188:in `destroy'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/associations/collection_association.rb:165:in `destroy_all'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/associations/has_many_association.rb:28:in `handle_dependency'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/associations/builder/association.rb:141:in `block in add_destroy_callbacks'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:467:in `instance_exec'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:467:in `block in make_lambda'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:687:in `block (2 levels) in default_terminator'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:686:in `catch'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:686:in `block in default_terminator'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:200:in `block in halting'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:595:in `block in invoke_before'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:595:in `each'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:595:in `invoke_before'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:106:in `run_callbacks'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/acts_as_paranoid-0.10.2/lib/acts_as_paranoid/core.rb:173:in `block in destroy'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/acts_as_paranoid-0.10.2/lib/acts_as_paranoid/core.rb:172:in `destroy'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/relation/batches.rb:71:in `each'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/relation/batches.rb:71:in `block in find_each'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/relation/batches.rb:138:in `block in find_in_batches'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/relation/batches.rb:245:in `block in in_batches'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/relation/batches.rb:229:in `loop'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/relation/batches.rb:229:in `in_batches'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/relation/batches.rb:137:in `find_in_batches'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/relation/batches.rb:70:in `find_each'
     # /Users/tomcoquery/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.8.4/lib/active_record/querying.rb:22:in `find_each'
```

3. The error disappears if I remove the gem and do a regular rails destroy (on rails 7). The error is also present if i stay on rails 6.1 and update acts_as_paranoid to 0.8.

**Comment by mvz** [comment]
Thanks @tomcoquery. One final question: Which version of acts_as_paranoid were you running before the update?

**Comment by mvz** [comment]
I can reproduce this. I did have to add `belongs_to` to the Collaboration class, but I'm sure that's present in the full code. When I remove the `acts_as_paranoid` calls, the error goes away. _However_, even in that case the records are not destroyed!

The reason is that `dependent: :destroy` adds its own callback to the `Program` class that destroys the `Collaboration` records. This callback is called before the custom `destroy_collaborations` callback, so before `skip_before_destroy` is set.

To make this work again, you need to swap the `before_destroy` and `has_many` lines, so the code will look like this:

```ruby
before_destroy :destroy_collaborations
has_many :collaborations, foreign_key: "program_id", dependent: :destroy
```

**Comment by tomcoquery** [comment]
Brilliant, this indeed fixes the problem. Thank you for taking the time to investigate.
