### ISSUE TITLE
NameError: undefined method `validate_find_options' for class `Class'

### ISSUE THREAD

**Issue by McRip** [ActsAsParanoid/acts_as_paranoid#36]
I have just integrated the gem into the Gemfile of my Rails 4.2.4 Application, and this is what i got when trying to restart the development server. Is this a compatibility issue?

Stacktrace:
```
Uncaught exception: undefined method `validate_find_options' for class `Class'
	/Users/moritzkroger/Documents/dev/megatron/vendor/ruby/2.2.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:42:in `alias_method'
	/Users/moritzkroger/Documents/dev/megatron/vendor/ruby/2.2.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:42:in `singleton class'
	/Users/moritzkroger/Documents/dev/megatron/vendor/ruby/2.2.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:41:in `included'
	/Users/moritzkroger/Documents/dev/megatron/vendor/ruby/2.2.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:166:in `include'
	/Users/moritzkroger/Documents/dev/megatron/vendor/ruby/2.2.0/gems/acts_as_paranoid-0.3.1/lib/acts_as_paranoid.rb:166:in `<top (required)>'
	/Users/moritzkroger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	/Users/moritzkroger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	/Users/moritzkroger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	/Users/moritzkroger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	/Users/moritzkroger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	/Users/moritzkroger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	/Users/moritzkroger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	/Users/moritzkroger/Documents/dev/megatron/config/application.rb:7:in `<top (required)>'
	/Users/moritzkroger/Documents/dev/megatron/vendor/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:78:in `require'
	/Users/moritzkroger/Documents/dev/megatron/vendor/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	/Users/moritzkroger/Documents/dev/megatron/vendor/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `tap'
	/Users/moritzkroger/Documents/dev/megatron/vendor/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `server'
	/Users/moritzkroger/Documents/dev/megatron/vendor/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	/Users/moritzkroger/Documents/dev/megatron/vendor/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	/Users/moritzkroger/Documents/dev/megatron/bin/rails:4:in `require'
	/Users/moritzkroger/Documents/dev/megatron/bin/rails:4:in `<top (required)>'
```

**Comment by hojberg** [comment]
Having this issue as well.

**Comment by zzak** [comment]
It looks like you (bundler) have activated an older version of the gem "`acts_as_paranoid-0.3.1`" based on the log you pasted.

Could you verify?

**Comment by eidge** [comment]
Yup, using ```gem 'acts_as_paranoid', github: 'ActsAsParanoid/acts_as_paranoid'``` solves it for me.

I wonder why bundler is using an older version though.

**Comment by zzak** [comment]
I'm not sure, maybe it was cached in your Gemfile.lock?

Please re-open this issue if you have any trouble with the release.

Thanks!

**Comment by ychaker** [comment]
Hey,
just wanted to report that I had the same issue, with a fresh install (no previous mention of the gem in the `Gemfile` or `Gemfile.lock`).

had to use `gem 'acts_as_paranoid', github: 'ActsAsParanoid/acts_as_paranoid'` to get around it.

**Comment by zzak** [comment]
@ychaker The gem is still in pre-release state, so you will have to add the **exact** version to your Gemfile in order to get it.
